# Official pacman packages
PACKAGES = [
    # Base system
    "base",
    "base-devel",
    "linux",
    "linux-headers",
    "linux-firmware",
    "vim",
    "git",
    "htop",
    "less",
    "meson",
    "python",
    "rust",
    "archlinux-keyring",
    "ntfs-3g",
    "fastfetch",
    "curl",
    "wget",
    "sudo",
    "intel-ucode",

    # WM & Display
    "bspwm",
    "sxhkd",
    "xorg-server",
    "xorg-xinit",
    "xorg-xrandr",
    "xorg-xsetroot",
    "xorg-xbacklight",
    "xorg-xset",
    "xorg-xinput",
    "xorg-xprop",
    "xorg-xkill",
    "xorg-xev",
    "xorg-xdpyinfo",
    "lightdm",
    "lightdm-gtk-greeter",
    "picom",
    "polybar",
    "rofi",
    "rofi-calc",
    "rofi-emoji",
    "dunst",
    "dmenu",

    # Terminal & Shell
    "alacritty",
    "zsh",
    "tmux",

    # Fonts
    "ttf-cascadia-mono-nerd",
    "ttf-cascadia-code-nerd",
    "ttf-jetbrains-mono-nerd",
    "ttf-firacode-nerd",
    "ttf-hack-nerd",
    "ttf-meslo-nerd",
    "ttf-iosevka-nerd",
    "ttf-roboto-mono-nerd",
    "ttf-ubuntu-mono-nerd",
    "ttf-sourcecodepro-nerd",
    "ttf-ibmplex-mono-nerd",
    "ttf-nerd-fonts-symbols-mono",
    "noto-fonts-emoji",
    "powerline-fonts",

    # File manager & utilities
    "thunar",
    "tumbler",
    "ffmpegthumbnailer",
    "udisks2",
    "udiskie",
    "ueberzugpp",
    "xarchiver",
    "unrar",
    "zip",
    "unzip",
    "p7zip",
    "sshfs",
    "xclip",
    "fd",
    "ripgrep",
    "bat",
    "tree",
    "jq",
    "imagemagick",
    "scrot",
    "slop",

    # Audio
    "pulseaudio",
    "pulseaudio-bluetooth",
    "alsa-utils",
    "alsa-plugins",
    "alsa-tools",
    "pamixer",
    "pavucontrol",
    "wireplumber",

    # Bluetooth
    "bluez-utils",
    "blueman",

    # Network
    "networkmanager",
    "openssh",
    "iwd",
    "netctl",
    "net-tools",
    "nmap",
    "bind",

    # GPU / Display drivers
    "nvidia-utils",
    "lib32-nvidia-utils",
    "nvidia-settings",
    "xf86-video-intel",
    "vulkan-intel",

    # Theming
    "papirus-icon-theme",
    "lxappearance",
    "nwg-look",
    "xfce4-settings",
    "breeze",
    "polkit-qt6",

    # Applications
    "firefox",
    "google-chrome",
    "telegram-desktop",
    "obs-studio",
    "vlc",
    "mpv",
    "libreoffice-fresh",
    "evince",
    "zathura",
    "zathura-djvu",
    "zathura-pdf-mupdf",
    "flameshot",
    "screenkey",
    "feh",
    "nitrogen",

    # Development
    "code",
    "clang",
    "jdk-openjdk",
    "python-pip",
    "python-pyqt5",
    "python-pyalsa",
    "python-pywal",
    "qt5-base",
    "postgresql",
    "docker",
    "docker-compose",
    "arduino-cli",
    "lazygit",
    "sqlitebrowser",

    # TUI tools
    "btop",
    "yazi",
    "lazydocker",
    "calcurse",
    "ncmpcpp",
    "mpd",
    "mpc",
    "cava",

    # System tools
    "brightnessctl",
    "light",
    "redshift",
    "reflector",
    "timeshift",
    "gparted",
    "gnome-disk-utility",
    "gufw",
    "usbutils",
    "i2c-tools",
    "xfce4-power-manager",

    # Media / Creative
    "kdenlive",
    "audacity",
    "ffmpeg",
    "gphoto2",
    "piper",

    # Productivity
    "obsidian",
    "keepassxc",
    "homebank",
    "gnome-calculator",
    "gnome-clocks",
    "calc",
    "gnome-clocks",

    # Privacy & Security
    "veracrypt",
    "mat2",
    "bleachbit",
    "wireshark-qt",

    # Python tools
    "bpython",
    "ipython",

    # Misc
    "wofi",
    "poppler",
    "seatd",
    "shellcheck",
    "cowsay",
    "cloc",
    "deluge-gtk",
    "filezilla",
    "ghex",
    "gpick",
    "gucharmap",
    "gthumb",
    "gtkhash",
    "dconf-editor",
    "pinta",
    "touche",
    "mat2",
    "mtools",
    "sdl2-compat",
    "sdl2_image",
    "qemu-base",
]

# AUR packages (installed via yay)
AUR_PACKAGES = [
    "zsh-theme-powerlevel10k-git",
    "catppuccin-cursors-macchiato",
    "papirus-folders-catppuccin-git",
    "openrgb-git",
    "optimus-manager-git",
    "rofi-bluetooth-git",
    "google-chrome",
    "yandex-music",
    "nekoray-bin",
    "arduino-ide-bin",
    "gtk-engine-murrine",
    "wlroots-asan-git",
    "bluetui",
    "impala",
]
