#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
thunar --daemon &
pkill udiskie; udiskie -t &
$HOME/bin/screenlayout.sh &

# workspaces
bspc monitor default -d 1 2 3 4 5 6 7 8 9

bspc config focus_follows_pointer true

bspc config automatic_scheme alternate
bspc config initial_polarity second_child

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 3
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# gaps
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config split_ratio 0.5

# rules
bspc rule -a feh state=floating

# start resources
xrdb merge ~/.config/Xresources

# python script to always initialize with a different wallpaper:

~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# autostart
flameshot &