#! /bin/sh

# Start sxhkd if it's not already running
# pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -layout us,ru -option grp:win_space_toggle

# Start background services
thunar --daemon &
pkill udiskie; udiskie -t &
$HOME/.screenlayout/display.sh &

# Configure workspaces
bspc monitor DP-4 -d 1 2 3 4 5 6
bspc monitor DP-2 -d 7 8
bspc monitor HDMI-0 -d 9

# BSPWM settings
bspc config focus_follows_pointer true
bspc config automatic_scheme alternate
bspc config initial_polarity second_child

# Window borders
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 3
bspc config borderless_monocle true
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# Fix cursor
xsetroot -cursor_name left_ptr

# Gaps configuration
bspc config gapless_monocle false
bspc config window_gap 17

# Move and resize floating windows with mouse (Mod4 is Win/Super key)
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config split_ratio 0.5

# Load Xresources
xrdb merge ~/.config/Xresources

# Launch background scripts
~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh &

# Start notification daemon
dunst -conf $HOME/.config/bspwm/dunstrc &

# Launch battery tracker and color correction
pkill battery-alert; ~/.bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# Start compositor
picom --config $HOME/.config/picom/picom.conf &

# Autostart applications
flameshot &
openrgb -p $HOME/.openrgb/tyom_old.orp &

# Fix Chrome error
rm -rf ~/.config/google-chrome/Singleton*
